name: Deploy next.js application to AWS EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create .env.production
      run: |
        echo "API_URL=${{ secrets.NEXT_API_URL }}" >> .env.production

    # DockerHub login
    - name: login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Docker image build
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-client .

    # DockerHub 이미지 푸시
    - name: docker hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-client

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
      # Target IP 설정
      - name: Set target IP
        run: |
          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.LIVE_SERVER_IP }}/api/hc/env")
          echo "STATUS: $STATUS"
          echo $STATUS
          exit 1
          
