name: Deploy next.js application to AWS EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create .env.production
      run: |
        echo "API_URL=${{ secrets.NEXT_API_URL }}" >> .env.production

    # DockerHub login
    - name: login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Docker image build
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-client .

    # DockerHub 이미지 푸시
    - name: docker hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-client

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
      # Target IP 설정
      - name: Set target IP
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            CONTAINER_NAME=$(sudo docker ps --format '{{.Names}}' | grep -E 'alpha|beta')
  
            if [ -n "$CONTAINER_NAME" ]; then
              echo "Current Container Name: $CONTAINER_NAME"
              echo "CURRENT_UPSTREAM: $CONTAINER_NAME"
            else
              CURRENT_UPSTREAM=beta
            fi
            
            echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
            if [ $CURRENT_UPSTREAM = alpha ]; then
              echo "CURRENT_PORT=3000" >> $GITHUB_ENV
              echo "STOPPED_PORT=3001" >> $GITHUB_ENV
              echo "TARGET_UPSTREAM=beta" >> $GITHUB_ENV
            else
              echo "CURRENT_PORT=3001" >> $GITHUB_ENV
              echo "STOPPED_PORT=3000" >> $GITHUB_ENV
              echo "TARGET_UPSTREAM=alpha" >> $GITHUB_ENV
            fi

      # Docker Compose 실행    
      - name: Docker compose
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-client:latest
            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d

      # 실행한 배포 서버 확인
      - name: Check deploy server URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://${{ secrets.LIVE_SERVER_IP }}:${{env.STOPPED_PORT}}/
          max-attempts: 3
          retry-delay: 10s
          
      # 새로운 배포 서버(컨테이너)로 교체
      - name: Change nginx upstream
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker exec -i nginxserver bash -c 'sed -i "s/set \$service_url .*/set \$service_url ${{ env.TARGET_UPSTREAM }};/" /etc/nginx/conf.d/service-env.inc && nginx -s reload'

      # 교체완료시 기존 서버(컨테이너) 중지
      - name: Stop current server
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            echo "Stopping current container: ${{env.CURRENT_UPSTREAM}}"
            sudo docker stop ${{env.CURRENT_UPSTREAM}} 2>/dev/null || true
            echo "Removing current container: ${{env.CURRENT_UPSTREAM}}"
            sudo docker rm ${{env.CURRENT_UPSTREAM}} 2>/dev/null || true
            sudo docker image prune -a -f    
          
